DEPENDS_append_toolchain-clang = " clang-cross-${TARGET_ARCH}"
DEPENDS_remove_toolchain-clang = "virtual/${TARGET_PREFIX}gcc"
TOOLCHAIN_x86-x32 = "gcc"
TOOLCHAIN_riscv64 = "gcc"
TOOLCHAIN_powerpc64 = "gcc"
